site_url: http://hillstoneUnited.github.com/rcss3dMotionEditor/
project_url: http://github.com/hillstoneUnited/rcss3dMotionEditor/
title: hillstoneUnited rcss3dMotionEditor
author: hillstoneUnited
project_name: rcss3dMotionEditor
